//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.PetHotelORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInvoiceList
    {
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string speciesName { get; set; }
        public string petName { get; set; }
        public string employee { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> total { get; set; }
    }
}
