//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.PetHotelORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPetList
    {
        public string petName { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public int speciesID { get; set; }
        public Nullable<int> age { get; set; }
    }
}
